version: "3.9"
services:
  main:
    container_name: mainUser
    build:
      context: .
    env_file:
      - .docker.env
    ports:
      - 5022:5022
    command: npm run start:docker
    depends_on:
      - postgres
#      - rabbitmq
  postgres:
    container_name: postgresUser
    image: postgres:14
    environment:
      POSTGRES_DB: "dbKinopoiskUser"
      POSTGRES_USER: "pgUser"
      POSTGRES_PASSWORD: "123456"
#      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5434:5432
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
    ports:
      - 5672:5672
      - 15672:15672